apiVersion: apps/v1
kind: Deployment
metadata:
  name: sda-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sda-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi

