apiVersion: v1
kind: ConfigMap
metadata:
  name: sda-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.environment }}
    environment: {{ .Values.environment | quote }}
    {{- end }}
data:
  SDA_CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  {{- if .Values.config.otelExporterOtlpEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterOtlpEndpoint | quote }}
  {{- end }}

