apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sda-upload-store
  namespace: sda-lab5
  labels:
    app.kubernetes.io/name: sda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sda-analysis-store
  namespace: sda-lab5
  labels:
    app.kubernetes.io/name: sda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

