apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sda-upload-store
spec:
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sda-analysis-store
spec:
  resources:
    requests:
      storage: 5Gi

