apiVersion: v1
kind: Service
metadata:
  name: telegram-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: telegram-support-bot
    component: frontend
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- if .Values.environment }}
    environment: {{ .Values.environment | quote }}
    {{- end }}
spec:
  selector:
    app: telegram-support-bot
    component: frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
